# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - openvolunteeringapi

env:
  AZURE_WEBAPP_NAME: Query
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '5'                 # set this to the .NET Core version to use


on:
  push:
    branches:
      - nope
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: dotnet build Query --configuration Release

      - name: dotnet publish
        run: dotnet publish Query -c Release --output Query/published

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_60342768C2E6402F8107EA7317518A7E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9CC34914B1764EE8AB5CF0815FEA4C4B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_082FC03842724373AA163A431CA996D6 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'openvolunteeringapi'
          slot-name: 'Production'
          package: Query/published
